### ISSUE TITLE
focusFirstSuggestion doesn't clear input value

### ISSUE THREAD

**Issue by hanford** [gregchamberlain/react-chips#5]
Hey, first of all thanks for the library. I'm already using `react-autosuggest` and this fits perfectly next to it! 🤗

However, when using `focusFirstSuggestion` (basically focuses the first selection), and hitting `[enter]` the value is selected, however the value isn't cleared. Here is an example: http://d.pr/v/LcOR

**Comment by gregchamberlain** [comment]
Glad your enjoying the library! Thanks for the video, it really helps explain the issue. Should be an easy fix, so I'll look into it and probably have an update published later tonight.

**Comment by hanford** [comment]
yeah, glanced through the code but couldn't find a the clear codepath to do this. If you point me in the right direction I can open a PR

**Comment by gregchamberlain** [comment]
I got caught up in some extra work this week, so that would be awesome!

It looks like the issue might be that `AutoSuggest`'s input is calling `onChange` after the chip is added, changing the value to whatever was focused. 

A fix could be to check `this.state.value` against `value` in `addChip` and if they are not the same set some flag (perhaps `this.focusAdded`) to `true`. Then in `onChange` if `this.focusAdded` is `true` set `this.focusAdded` to false and `return`.

**Comment by gregchamberlain** [comment]
Sorry for the long wait, just fixed this in v0.5.0.

FYI I updated `react-autosuggest` to v9, which changed `focusFirstSuggestion` to`highlightFirstSuggestion` so you'll need to use that now.

Thanks for the patience!

**Comment by hanford** [comment]
👍
