### ISSUE TITLE
breaks with radium v0.18.2

### ISSUE THREAD

**Issue by dkanas** [gregchamberlain/react-chips#6]
With radium 0.18.2 the following error appears:
`Uncaught TypeError: Super expression must either be null or a function, not undefined`
Works, when radium is rolled back to 0.18.1 :)

**Comment by gregchamberlain** [comment]
Huh, interesting. Thanks for letting me know!

I think this may be an issue with Radium perhaps not having the correct React dependency version. I've run into this problem before on other projects. It happens when a Component tries to inherit from [React.PureComponent](https://facebook.github.io/react/docs/react-api.html#react.purecomponent), (added in React `v15.3`) and you're running an older version of react.

Try upgrading the version of React your project is using to >= 15.3 and it should fix the problem! :smile:

**Comment by dkanas** [comment]
Ok, will try that, thanks 😄
